server.port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

#  datasource:
#    url: jdbc:sqlserver://DESKTOP-C1V4R2D;databaseName=RemotePatientControl
#    username: user
#    password: u
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    show-sql: true
#    hibernate:
#      dialect: org.hibernate.dialect.SQLServer2012Dialect
#      ddl-auto: none